# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ByuGrades.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ByuGradesWindow(object):
    def setupUi(self, ByuGradesWindow):
        ByuGradesWindow.setObjectName(_fromUtf8("ByuGradesWindow"))
        ByuGradesWindow.resize(600, 600)
        self.centralwidget = QtGui.QWidget(ByuGradesWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.username_label = QtGui.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(157, 10, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.username_label.setFont(font)
        self.username_label.setObjectName(_fromUtf8("username_label"))
        self.username_input = QtGui.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(287, 10, 161, 22))
        self.username_input.setObjectName(_fromUtf8("username_input"))
        self.username_label_2 = QtGui.QLabel(self.centralwidget)
        self.username_label_2.setGeometry(QtCore.QRect(157, 50, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.username_label_2.setFont(font)
        self.username_label_2.setObjectName(_fromUtf8("username_label_2"))
        self.password_input = QtGui.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(287, 50, 161, 22))
        self.password_input.setInputMask(_fromUtf8(""))
        self.password_input.setEchoMode(QtGui.QLineEdit.Password)
        self.password_input.setObjectName(_fromUtf8("password_input"))
        self.username_label_3 = QtGui.QLabel(self.centralwidget)
        self.username_label_3.setGeometry(QtCore.QRect(157, 90, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.username_label_3.setFont(font)
        self.username_label_3.setObjectName(_fromUtf8("username_label_3"))
        self.semester_input = QtGui.QComboBox(self.centralwidget)
        self.semester_input.setGeometry(QtCore.QRect(287, 100, 161, 22))
        self.semester_input.setObjectName(_fromUtf8("semester_input"))
        self.semester_input.addItem(_fromUtf8(""))
        self.semester_input.addItem(_fromUtf8(""))
        self.semester_input.addItem(_fromUtf8(""))
        self.semester_input.addItem(_fromUtf8(""))
        self.semester_input.addItem(_fromUtf8(""))
        self.semester_input.addItem(_fromUtf8(""))
        self.username_label_4 = QtGui.QLabel(self.centralwidget)
        self.username_label_4.setGeometry(QtCore.QRect(157, 160, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.username_label_4.setFont(font)
        self.username_label_4.setObjectName(_fromUtf8("username_label_4"))
        self.year_input = QtGui.QLineEdit(self.centralwidget)
        self.year_input.setGeometry(QtCore.QRect(287, 160, 161, 22))
        self.year_input.setObjectName(_fromUtf8("year_input"))
        self.grades_button = QtGui.QPushButton(self.centralwidget)
        self.grades_button.setGeometry(QtCore.QRect(250, 260, 101, 23))
        self.grades_button.setObjectName(_fromUtf8("grades_button"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 340, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 380, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gpa_output = QtGui.QLabel(self.centralwidget)
        self.gpa_output.setGeometry(QtCore.QRect(65, 340, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.gpa_output.setFont(font)
        self.gpa_output.setText(_fromUtf8(""))
        self.gpa_output.setObjectName(_fromUtf8("gpa_output"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 290, 600, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 320, 601, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.save_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.save_checkbox.setGeometry(QtCore.QRect(250, 210, 101, 17))
        self.save_checkbox.setObjectName(_fromUtf8("save_checkbox"))
        self.classes_output = QtGui.QPlainTextEdit(self.centralwidget)
        self.classes_output.setGeometry(QtCore.QRect(10, 410, 581, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.classes_output.setFont(font)
        self.classes_output.setObjectName(_fromUtf8("classes_output"))
        self.clear_button = QtGui.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(250, 230, 101, 23))
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.username_input.raise_()
        self.username_label_2.raise_()
        self.password_input.raise_()
        self.username_label_3.raise_()
        self.semester_input.raise_()
        self.username_label_4.raise_()
        self.year_input.raise_()
        self.grades_button.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.save_checkbox.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.username_label.raise_()
        self.gpa_output.raise_()
        self.classes_output.raise_()
        self.clear_button.raise_()
        ByuGradesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ByuGradesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExportToFile = QtGui.QMenu(self.menuFile)
        self.menuExportToFile.setObjectName(_fromUtf8("menuExportToFile"))
        self.menuHelp_2 = QtGui.QMenu(self.menubar)
        self.menuHelp_2.setObjectName(_fromUtf8("menuHelp_2"))
        ByuGradesWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ByuGradesWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ByuGradesWindow.setStatusBar(self.statusbar)
        self.actionToTxt = QtGui.QAction(ByuGradesWindow)
        self.actionToTxt.setObjectName(_fromUtf8("actionToTxt"))
        self.actionToCsv = QtGui.QAction(ByuGradesWindow)
        self.actionToCsv.setObjectName(_fromUtf8("actionToCsv"))
        self.actionAbout = QtGui.QAction(ByuGradesWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(ByuGradesWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionVersion_0_1 = QtGui.QAction(ByuGradesWindow)
        self.actionVersion_0_1.setEnabled(False)
        self.actionVersion_0_1.setObjectName(_fromUtf8("actionVersion_0_1"))
        self.actionSave = QtGui.QAction(ByuGradesWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuExportToFile.addAction(self.actionToTxt)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.menuExportToFile.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuHelp_2.addAction(self.actionAbout)
        self.menuHelp_2.addSeparator()
        self.menuHelp_2.addAction(self.actionVersion_0_1)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(ByuGradesWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), ByuGradesWindow.close)
        QtCore.QMetaObject.connectSlotsByName(ByuGradesWindow)

    def retranslateUi(self, ByuGradesWindow):
        ByuGradesWindow.setWindowTitle(_translate("ByuGradesWindow", "BYU Grades", None))
        self.username_label.setText(_translate("ByuGradesWindow", "Username:", None))
        self.username_label_2.setText(_translate("ByuGradesWindow", "Password:", None))
        self.username_label_3.setText(_translate("ByuGradesWindow", "Target\n"
"Semester:", None))
        self.semester_input.setItemText(0, _translate("ByuGradesWindow", "Semester", None))
        self.semester_input.setItemText(1, _translate("ByuGradesWindow", "All", None))
        self.semester_input.setItemText(2, _translate("ByuGradesWindow", "Fall", None))
        self.semester_input.setItemText(3, _translate("ByuGradesWindow", "Winter", None))
        self.semester_input.setItemText(4, _translate("ByuGradesWindow", "Spring", None))
        self.semester_input.setItemText(5, _translate("ByuGradesWindow", "Summer", None))
        self.username_label_4.setText(_translate("ByuGradesWindow", "Year:", None))
        self.grades_button.setText(_translate("ByuGradesWindow", "Get Grades", None))
        self.label_2.setText(_translate("ByuGradesWindow", "GPA:", None))
        self.label_3.setText(_translate("ByuGradesWindow", "Classes and Grades:", None))
        self.label.setText(_translate("ByuGradesWindow", "Results", None))
        self.save_checkbox.setText(_translate("ByuGradesWindow", "Save Inforamtion", None))
        self.clear_button.setText(_translate("ByuGradesWindow", "Clear", None))
        self.menuFile.setTitle(_translate("ByuGradesWindow", "File", None))
        self.menuExportToFile.setTitle(_translate("ByuGradesWindow", "Export output to file...", None))
        self.menuHelp_2.setTitle(_translate("ByuGradesWindow", "Help", None))
        self.actionToTxt.setText(_translate("ByuGradesWindow", "To .txt", None))
        self.actionToTxt.setShortcut(_translate("ByuGradesWindow", "Ctrl+T", None))
        self.actionToCsv.setText(_translate("ByuGradesWindow", "To .csv", None))
        self.actionToCsv.setShortcut(_translate("ByuGradesWindow", "Ctrl+E", None))
        self.actionAbout.setText(_translate("ByuGradesWindow", "About", None))
        self.actionExit.setText(_translate("ByuGradesWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("ByuGradesWindow", "Ctrl+Q", None))
        self.actionVersion_0_1.setText(_translate("ByuGradesWindow", "Version 0.1", None))
        self.actionSave.setText(_translate("ByuGradesWindow", "Save Output", None))
        self.actionSave.setShortcut(_translate("ByuGradesWindow", "Ctrl+S", None))

